### ISSUE TITLE
SQL Error when using plugin in Trino 448 and 449

### ISSUE THREAD

**Issue by swestdijk** [nineinchnick/trino-openapi#100]
Hi, 

Using this plugin with the openmeteo site I got this error when installed in trino 448 and 449.

SQL Error [65536]: Query failed (#20240601_052641_00010_q9zan): class io.trino.spi.block.VariableWidthBlock cannot be cast to class io.trino.spi.block.SqlRow (io.trino.spi.block.VariableWidthBlock and io.trino.spi.block.SqlRow are in unnamed module of loader 'app')

Installation method is the same. So no clue whats happening here.

Sjaak

**Comment by nineinchnick** [comment]
Fixed in 385748262b13f286f2b6330160472f7faed867c1. Thanks for reporting this, it's a regression I introduced recently. I added a new test to avoid this happening again.

**Comment by nineinchnick** [comment]
Please try v1.51

**Comment by swestdijk** [comment]
Thanks a log, its working again.
