### ISSUE TITLE
Unable to configure JIRA catalog using openapi connector

### ISSUE THREAD

**Issue by saurabh-shinde** [nineinchnick/trino-openapi#33]
While trying to configure JIRA catalog on trino(version 423), we are getting below error:

> 2023-11-06T12:55:35.223Z	ERROR	main	io.trino.server.Server	Unable to create injector, see the following errors:
> 
> 1) [Guice/ErrorInjectingConstructor]: NullPointerException: Cannot invoke "io.swagger.v3.oas.models.media.Schema.getRequired()" because "schema" is null
>   at OpenApiSpec.<init>(OpenApiSpec.java:89)
>   at GeneratedMethodAccessor110.invoke(Unknown Source)
>   at Authentication.<init>(Authentication.java:78)
>       \_ for 2nd parameter spec
>   while locating Authentication
>   while locating HttpRequestFilter annotated with @Element(setName=@ForOpenApi,uniqueId=6, type=MULTIBINDER, keyType=)
>   while locating Set<HttpRequestFilter> annotated with interface ForOpenApi
>   at HttpClientModule.configure(HttpClientModule.java:76)
>       \_ installed by: OpenApiModule -> HttpClientModule
>   while locating HttpClient annotated with interface ForOpenApi
> 
> Learn more:
>   https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
> Caused by: NullPointerException: Cannot invoke "io.swagger.v3.oas.models.media.Schema.getRequired()" because "schema" is null
> 	at OpenApiSpec.lambda$getColumns$19(OpenApiSpec.java:224)
> 	at java.base/ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
> 	at java.base/Iterator.forEachRemaining(Iterator.java:133)
> 	at java.base/Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
> 	at java.base/AbstractPipeline.copyInto(AbstractPipeline.java:509)
> 	at java.base/AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
> 	at java.base/AbstractPipeline.evaluate(AbstractPipeline.java:575)
> 	at java.base/AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
> 	at java.base/ReferencePipeline.toArray(ReferencePipeline.java:616)
> 	at java.base/ReferencePipeline.toArray(ReferencePipeline.java:622)
> 	at java.base/ReferencePipeline.toList(ReferencePipeline.java:627)
> 	at OpenApiSpec.getColumns(OpenApiSpec.java:288)
> 	at OpenApiSpec.lambda$new$2(OpenApiSpec.java:99)
> 	at java.base/Collectors.lambda$toMap$68(Collectors.java:1674)
> 	at java.base/ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
> 	at java.base/ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
> 	at java.base/Iterator.forEachRemaining(Iterator.java:133)
> 	at java.base/Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
> 	at java.base/AbstractPipeline.copyInto(AbstractPipeline.java:509)
> 	at java.base/AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
> 	at java.base/ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
> 	at java.base/AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.base/ReferencePipeline.collect(ReferencePipeline.java:682)
> 	at OpenApiSpec.<init>(OpenApiSpec.java:97)
> 	at OpenApiSpec$$FastClassByGuice$$7b9e35.GUICE$TRAMPOLINE(<generated>)
> 	at OpenApiSpec$$FastClassByGuice$$7b9e35.apply(<generated>)
> 	at DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
> 	at ConstructorInjector.provision(ConstructorInjector.java:114)
> 	at ConstructorInjector.access$000(ConstructorInjector.java:33)
> 	at ConstructorInjector$1.call(ConstructorInjector.java:98)
> 	at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
> 	at LifeCycleModule.provision(LifeCycleModule.java:53)
> 	at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
> 	at ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
> 	at ConstructorInjector.construct(ConstructorInjector.java:93)
> 	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
> 	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
> 	at SingletonScope$1.get(SingletonScope.java:169)
> 	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
> 	at SingleParameterInjector.inject(SingleParameterInjector.java:40)
> 	at SingleParameterInjector.getAll(SingleParameterInjector.java:60)
> 	at ConstructorInjector.provision(ConstructorInjector.java:113)
> 	at ConstructorInjector.access$000(ConstructorInjector.java:33)
> 	at ConstructorInjector$1.call(ConstructorInjector.java:98)
> 	at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
> 	at LifeCycleModule.provision(LifeCycleModule.java:53)
> 	at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
> 	at ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
> 	at ConstructorInjector.construct(ConstructorInjector.java:93)
> 	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
> 	at FactoryProxy.get(FactoryProxy.java:60)
> 	at SingleParameterInjector.inject(SingleParameterInjector.java:40)
> 	at RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:247)
> 	at RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:213)
> 	at InternalProviderInstanceBindingImpl$Factory$1.call(InternalProviderInstanceBindingImpl.java:120)
> 	at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
> 	at LifeCycleModule.provision(LifeCycleModule.java:53)
> 	at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
> 	at ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
> 	at InternalProviderInstanceBindingImpl$Factory.get(InternalProviderInstanceBindingImpl.java:115)
> 	at InjectorImpl$1.get(InjectorImpl.java:1148)
> 	at InjectorImpl.getInstance(InjectorImpl.java:1181)
> 	at HttpClientModule$HttpClientProvider.get(HttpClientModule.java:142)
> 	at HttpClientModule$HttpClientProvider.get(HttpClientModule.java:93)
> 	at ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
> 	at InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:57)
> 	at ProviderInternalFactory$1.call(ProviderInternalFactory.java:67)
> 	at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
> 	at LifeCycleModule.provision(LifeCycleModule.java:53)
> 	at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
> 	at ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
> 	at ProviderInternalFactory.circularGet(ProviderInternalFactory.java:62)
> 	at InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:47)
> 	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
> 	at SingletonScope$1.get(SingletonScope.java:169)
> 	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
> 	at InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
> 	at InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
> 	at InternalInjectorCreator.build(InternalInjectorCreator.java:113)
> 	at Guice.createInjector(Guice.java:87)
> 	at Bootstrap.initialize(Bootstrap.java:268)
> 	at OpenApiConnectorFactory.create(OpenApiConnectorFactory.java:52)
> 	at DefaultCatalogFactory.createConnector(DefaultCatalogFactory.java:224)
> 	at DefaultCatalogFactory.createCatalog(DefaultCatalogFactory.java:133)
> 	at LazyCatalogFactory.createCatalog(LazyCatalogFactory.java:45)
> 	at StaticCatalogManager.lambda$loadInitialCatalogs$1(StaticCatalogManager.java:157)
> 	at java.base/FutureTask.run(FutureTask.java:264)
> 	at java.base/Executors$RunnableAdapter.call(Executors.java:539)
> 	at java.base/FutureTask.run(FutureTask.java:264)
> 	at DirectExecutor.execute(DirectExecutor.java:31)
> 	at java.base/ExecutorCompletionService.submit(ExecutorCompletionService.java:184)
> 	at Executors.executeUntilFailure(Executors.java:41)
> 	at StaticCatalogManager.loadInitialCatalogs(StaticCatalogManager.java:151)
> 	at Server.doStart(Server.java:144)
> 	at Server.lambda$start$0(Server.java:91)
> 	at io.trino.$gen.Trino_431____20231106_125507_1.run(Unknown Source)
> 	at Server.start(Server.java:91)
> 	at TrinoServer.main(TrinoServer.java:38)

We have set `authentication.type=http` and `authentication.scheme=basic`
Please note that we are able to call Jira APIs through curl, so network connectivity is fine.

**Comment by nineinchnick** [comment]
Fixed in https://github.com/nineinchnick/trino-openapi/commit/1587756304b0b797c0cd344392d5593c365416a7, thanks for reporting! There is a test for the Jira schema, but it's using a file I downloaded a while ago. They must have updated it.
