### ISSUE TITLE
Missing constraint errors for tables in JIRA catalog

### ISSUE THREAD

**Issue by saurabh-shinde** [nineinchnick/trino-openapi#34]
We are seeing missing constraints errors for tables present in JIRA catalog configured with help of openapi connector.

> o.trino.spi.TrinoException: Missing required constraint for key_req
>     at pl.net.was.OpenApiClient.lambda$getFilterValues$5(OpenApiClient.java:187)
>     at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
>     at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
>     at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
>     at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
>     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
>     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
>     at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
>     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
>     at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
>     at pl.net.was.OpenApiClient.getFilterValues(OpenApiClient.java:184)
>     at pl.net.was.OpenApiClient.makeRequest(OpenApiClient.java:129)
>     at pl.net.was.OpenApiClient.getRows(OpenApiClient.java:92)
>     at pl.net.was.OpenApiRecordSetProvider.getRecordSet(OpenApiRecordSetProvider.java:74)
>     at io.trino.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:50)
>     at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:61)
>     at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:296)
>     at io.trino.operator.Driver.processInternal(Driver.java:395)
>     at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
>     at io.trino.operator.Driver.tryWithLock(Driver.java:694)
>     at io.trino.operator.Driver.process(Driver.java:290)
>     at io.trino.operator.Driver.processForDuration(Driver.java:261)
>     at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
>     at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
>     at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:555)
>     at io.trino.$gen.Trino_423_e_5____20231108_120903_2.run(Unknown Source)
>     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
>     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
>     at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by nineinchnick** [comment]
This is expected, you have to include a predicate for this column in the query:
```
SELECT * FROM some_table WHERE key_req = 'some value';
```

**Comment by saurabh-shinde** [comment]
Hi @nineinchnick ,
Thanks for the help, I added conditions & the query is now failing with different error.

> java.lang.NullPointerException: bodyGenerator is null
> 	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
> 	at pl.net.was.authentication.Authentication.getToken(Authentication.java:235)
> 	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181)
> 	at pl.net.was.authentication.Authentication.applyOAuth(Authentication.java:220)
> 	at pl.net.was.authentication.Authentication.lambda$applyAuthFilters$0(Authentication.java:149)
> 	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
> 	at pl.net.was.authentication.Authentication.lambda$applyAuthFilters$1(Authentication.java:143)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
> 	at pl.net.was.authentication.Authentication.applyAuthFilters(Authentication.java:143)
> 	at pl.net.was.authentication.Authentication.filterRequest(Authentication.java:113)
> 	at io.airlift.http.client.jetty.JettyHttpClient.applyRequestFilters(JettyHttpClient.java:828)
> 	at io.airlift.http.client.jetty.JettyHttpClient.execute(JettyHttpClient.java:640)
> 	at pl.net.was.OpenApiClient.makeRequest(OpenApiClient.java:148)
> 	at pl.net.was.OpenApiClient.getRows(OpenApiClient.java:95)
> 	at pl.net.was.OpenApiRecordSetProvider.getRecordSet(OpenApiRecordSetProvider.java:74)
> 	at io.trino.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:50)
> 	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:61)
> 	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:296)
> 	at io.trino.operator.Driver.processInternal(Driver.java:395)
> 	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
> 	at io.trino.operator.Driver.tryWithLock(Driver.java:694)
> 	at io.trino.operator.Driver.process(Driver.java:290)
> 	at io.trino.operator.Driver.processForDuration(Driver.java:261)
> 	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
> 	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
> 	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:555)
> 	at io.trino.$gen.Trino_423_e_5____20231108_134814_2.run(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by nineinchnick** [comment]
Can you include your configuration for the connector?

**Comment by saurabh-shinde** [comment]
Hello,
PSB config for catalog.

> jira_openapi: |
>     connector.name=openapi
>     spec-location=/usr/lib/starburst/plugin/swagger-v3.v3.json
>     base-uri=https://<domain>.atlassian.net
>     authentication.type=http
>     authentication.scheme=basic
>     authentication.username=<username>
>     authentication.password=<api token>

**Comment by saurabh-shinde** [comment]
Hi @nineinchnick ,

I was able to get past this error by updating properties for catalog. 
Currently seeing a different error, will be updating it in a separate issue

```
  jira_openapi: |
    connector.name=openapi
    spec-location=<swagger json>
    base-uri=https://<domain>.atlassian.net
    authentication.type=http
    authentication.scheme=basic
    authentication.grant-type=BasicAuth
    authentication.username=<user-email>
    authentication.password=<api token>
    openApiAuthentication.http-client.log.enabled=true
    openApiAuthentication.http-client.log.path=/var/log/openapi_http_auth/
    openApi.http-client.log.enabled=true
    openApi.http-client.log.path=/var/log/openapi_http/
```
