### ISSUE TITLE
Unexpected constraint for longitude_req(real)

### ISSUE THREAD

**Issue by swestdijk** [nineinchnick/trino-openapi#50]
Hi,

I have this curl query: 

```bash
curl 'https://api.open-meteo.com/v1/forecast?latitude=51.9851&longitude=5.8987&hourly=temperature_2m&current_weather=true'
```

And this query to trino:

```sql
select 
	*
from
	openmeteo."default".v1_forecast 
where 
	latitude_req = 51.9851
and
	longitude_req = 5.58987
and 
	hourly = 'temperature_2m'
and 
	current_weather = 'true'
```

Then i got the Unexpected constraint for longitude_req(real) error messages. So whats going wrong.

My openmeteo.properties file:

```ini
connector.name=openapi
spec-location=https://raw.githubusercontent.com/open-meteo/open-meteo/main/openapi.yml
base-uri=https://api.open-meteo.com
openApi.http-client.log.enabled=true
openApi.http-client.log.path=/tmp
```

BTW, the log file is empty

What I am doing wrong ?

**Comment by nineinchnick** [comment]
Hi, thanks for reporting the issue! The connector was not able to handle predicates of type `REAL`. I fixed that in https://github.com/nineinchnick/trino-openapi/commit/eeb668623fd7ec75a9a1ed4e1188737fb174fcf5 and just released [v1.27](https://github.com/nineinchnick/trino-openapi/releases/tag/v1.27).

Also, you have too many predicates in the query, some of them are not even mentioned as parameters in the spec.

I ran this query:
```sql
select * from v1_forecast where latitude_req = 51.9851 and longitude_req = 5.58987;
```

And got this result:
```
 elevation  | hourly_units | generationtime_ms | daily_units | daily |  latitude   | utc_offset_seconds | hourly | longitude_req | current_weather | longitude  | latitude_req 
------------+--------------+-------------------+-------------+-------+-------------+--------------------+--------+---------------+-----------------+------------+--------------
 6.00000000 | NULL         |        0.00107288 | NULL        | NULL  | 51.98000000 |                  0 | NULL   |       7.0E-45 | NULL            | 5.57999940 |      7.1E-44 
(1 row)
```


The connector logs these HTTP request and response:

> 2023-12-30T14:51:43.695+0100	DEBUG	20231230_135142_00000_9n3qd.0.0.0-0-99	pl.net.was.OpenApiRecordSetProvider	Request URL: https://api.open-meteo.com/v1/forecast?latitude=51.9851&longitude=5.58987
> 2023-12-30T14:51:43.950+0100	DEBUG	20231230_135142_00000_9n3qd.0.0.0-0-99	pl.net.was.OpenApiRecordSetProvider	Received response code 200: {"latitude":51.98,"longitude":5.5799994,"generationtime_ms":0.00095367431640625,"utc_offset_seconds":0,"timezone":"GMT","timezone_abbreviation":"GMT","elevation":6.0}

So it looks like the API doesn't return any results for these coordinates. I tested it with my home town and also got nothing. I'll go and test other weather APIs now.

**Comment by nineinchnick** [comment]
BTW the logs saved to a separate file are kinda useless, since they only log the number of requests without any details. The logs I mentioned are printed in the Trino node logs.

**Comment by nineinchnick** [comment]
Ah I think the `current` and `hourly` predicates are also required, but are not even correctly mapped to columns so can't be provided right now. I'll fix it in the next release.

**Comment by nineinchnick** [comment]
Phew, done! I added handling of optional request parameters and improved type handling. This particular API defines types in a slightly different way than all the others I tested so far.

Now if I run this query on v1.28:
```sql
select * from v1_forecast where latitude_req = 51.9851 and longitude_req = 5.58987 and current_weather_req = true;
```

I get:
```
-[ RECORD 1 ]-------+--------------------------------------------------------------------------------------------------
elevation           | 6.00000000
hourly_req          | NULL
temperature_unit    | NULL
wind_speed_unit     | NULL
daily_units         | NULL
daily_req           | NULL
timezone            | GMT
latitude            | 51.98000000
timeformat          | NULL
current_weather_req | true
past_days           | NULL
hourly_units        | NULL
generationtime_ms   | 0.04696846
daily               | NULL
utc_offset_seconds  | 0
hourly              | NULL
longitude_req       | 7.0E-45
current_weather     | {time=2023-12-30T16:30, temperature=8.3, wind_speed=NULL, wind_direction=NULL, weather_code=NULL}
longitude           | 5.57999940
latitude_req        | 7.1E-44
```

Notice there's a bunch of new columns now for all optional request parameters. If you want a series of measurements, use the `hourly_req = array['temperature_2m']` predicate instead of `current_weather_req = true`.

**Comment by swestdijk** [comment]
Really thanks for the effort to fix this. Let see if i can test it this weekend.

**Comment by swestdijk** [comment]
Wow, this works very nice

select 
	time_stamp,
	temperature,
	windspeed
from 
	openmeteo."default".v1_forecast
CROSS JOIN UNNEST(hourly.time, hourly.temperature_2m, hourly.wind_speed_10m) AS t (time_stamp, temperature, windspeed) 
where 
	latitude_req = 51.98
and
	longitude_req = 5.911
and 
	hourly_req = array['temperature_2m', 'wind_speed_10m']

Thanks again
