### ISSUE TITLE
Nested JSON field in response for JIRA cloud API leads to query failure.

### ISSUE THREAD

**Issue by saurabh-shinde** [nineinchnick/trino-openapi#57]
Trino version: 435, 436
Connector version: 1.28, 1.29

We are trying to onboard JIRA catalog using this connector.
But on querying `rest_api_3_issue` table, we are seeing following error

`
2024-01-19T08:19:18.890Z	ERROR	SplitRunner-2-112	io.trino.execution.executor.timesharing.TimeSharingTaskExecutor	Error processing Split 20240119_081917_00000_y9m47.0.0.0-0 OpenApi split (start = 1992096.116699, wall = 865 ms, cpu = 0 ms, wait = 0 ms, calls = 1)
java.lang.ClassCastException: class com.fasterxml.jackson.databind.node.ObjectNode cannot be cast to class com.fasterxml.jackson.databind.node.ArrayNode (com.fasterxml.jackson.databind.node.ObjectNode and com.fasterxml.jackson.databind.node.ArrayNode are in unnamed module of loader io.trino.server.PluginClassLoader @4c29138a)
`

Query - `SELECT * FROM jira_openapi."default".rest_api_3_issue where issue_id_or_key='ATT-39';`

Config for this catalog - [jira_openapi.txt](https://github.com/nineinchnick/trino-openapi/files/13986443/jira_openapi.txt) 
Complete error log - [error-log-436.txt](https://github.com/nineinchnick/trino-openapi/files/13986442/error-log-436.txt)
API spec - [JIRA-openapi-doc.json](https://github.com/nineinchnick/trino-openapi/files/13986479/JIRA-openapi-doc.json)

**Comment by saurabh-shinde** [comment]
As per my understanding, error is happening due to incorrect column type for `fields` column.

Ideally it should be a `MAP` but it is set to `ARRAY(varchar)`

**Comment by saurabh-shinde** [comment]
Hi @nineinchnick ,

As a workaround to view data from columns with nested JSON data, we added a method to return JSON string as VARCHAR.

This will atleast allow users to view data & use JSON functions to query data in it

**Comment by nineinchnick** [comment]
Fixed by be3741888d4d5938184bcf7db2cf4bd1668f4399
