### ISSUE TITLE
Jira APIs failing due to URL encoding

### ISSUE THREAD

**Issue by saurabh-shinde** [nineinchnick/trino-openapi#65]
We are getting 400 response code on querying `rest_api_3_search` with `jql` parameter.

Query - `SELECT * FROM jira_openapi."default".rest_api_3_search where jql='project="IAMAEE" ORDER BY created DESC' LIMIT 10;`

This query forms API like this - `https://blah.atlassian.net/rest/api/3/search?jql=project%253D%2522IAMAEE%2522+ORDER+BY+created+DESC` which is invalid & leads to error.

Response is -
```
{
"errorMessages":["Error in the JQL Query: The character '%' is a reserved JQL character. You must enclose it in a string or use the escape '\\u0025' instead. (line 1, character 8)"],
"errors":{}
}
```

Correct API would look like - `https://blah.atlassian.net/rest/api/3/search?jql=project%3D%22IAMAEE%22+ORDER+BY+created+DESC`

**Comment by nineinchnick** [comment]
Fixed in 192e125c9f2ff72333f02a774f3b90239d21e47b

TIL that `java.net.URI` always encodes query parameters.
