### ISSUE TITLE
Missing column for request parameter if the API has both request parameter and POST body

### ISSUE THREAD

**Issue by nmkarvekar** [nineinchnick/trino-openapi#75]
Hi,

If we have any POST HTTP request having both request parameter and POST body, the request parameter doesn't get considered as a column. 

> OpenAPI specification example: 

```
paths:
  /employee:
    post:
      operationId: employee
      parameters:
        - name: request-id
          in: header
          description: Request Id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
        required: true       
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    Employee:
      type: object
      properties:
        name:
          type: string
        address:
          type: string     
```

In this example, the endpoint /employee is of type POST and it has both request parameter and request body. When we use this kind of specification in trino-openapi, request parameter doesn't get considered as a column.

When we execute the command "show create table employee" in trino CLI, we can only see address and name as columns. We should also get request-id as a column. 

If we change the endpoint type to GET, then there is no issue and we see both request parameter and request body attributes as columns.

**Comment by nineinchnick** [comment]
Fixed by 362e2a461385c9ed634294194b9c4ba0846ff4ef
